### ISSUE TITLE
Color for notification counter

### ISSUE THREAD

**Issue by richardHangHimself** [moehriegitt/NeatLauncher#12]
It is really neat launcher! I am trying to use it as a daily driver. Would it be possible to select color for the notification counter (just some selection as we have for font color)?

**Comment by moehriegitt** [comment]
There are no plans to have more configuration options right now -- I prefer to have one right way if possible, to make testing simple.  One of the design principles here is to have a very simple colour scheme, because it was one reason I wrote this: other launchers were too colourful.  One single accent colour, I think, makes it look elegant.  The notification counters are marked up by making them superscript.
