### ISSUE TITLE
Add uninstall option

### ISSUE THREAD

**Issue by ifearthelord** [moehriegitt/NeatLauncher#4]
When long-clicked on an app within the launcher, it'd be handy to have an uninstall option in the context menu that appears.

![Screenshot_20241025-153819230 (1)](https://github.com/user-attachments/assets/546ba42a-5ab1-4657-96dd-098952c71aef)

**Comment by moehriegitt** [comment]
This was a conscious safety and robustness decision.

The option to uninstall apps has not been left out on purpose, because it would require an additional permission, and a bug in the uninstall code could be disastrous, potentially uninstalling the wrong app or multiple of them, or whatever.  Without the 'uninstall app' permission, the launcher cannot be broken in such a way.

Also, I feel that there really is no need for this functionality, because uninstalling an app is just one more click away, via the 'App Info' system dialog, which has an 'uninstall app' function right at the top of the dialog.

**Comment by moehriegitt** [comment]
There are no plans to implement an 'uninstall app' feature, because it would make the app less safe, and the 'App Info' dialog already offers that functionality.

**Comment by ifearthelord** [comment]
Understandable
I respect this decision as you prefer stability over functionality.
